# Names of the properties in the {environment}-properties.json files
ENVIRONMENT = "environment"
NAME = "name"
LOGS_PATH = "logs_path"
PAAS = "paas"
KEYSTONE_URL = "keystone_url"
SDC_URL = "sdc_url"
PAASMANAGER_URL = "paasmanager_url"
VDC = "vdc"
TENANT = "tenant"
USER = "user"
PASSWORD = "password"
TIER_IMAGE = "tier_image"
TIER_NUM_MIN = "tier_num_min"
TIER_NUM_MAX = "tier_num_max"
TIER_NUM_INITIAL = "tier_num_initial"
TIER_FLAVOUR = "tier_flavour"
TIER_KEYPAIR = "tier_keypair"
TIER_FLOATINGIP = "tier_floatingip"

# Auxiliary constants used in .feature files or interfaces
NAME = "name"
DESCRIPTION = "description"
PRODUCTS = "products"
NETWORKS = "networks"
